apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flyteadmin-ingress
  namespace: flyte
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  rules:
  - host: flyteadmin.local.flyte.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flyteadmin
            port:
              number: 81
