minio:
  enabled: true
  accessKey: minioadmin
  secretKey: minioadmin

postgres:
  enabled: true
  postgresUser: flyte
  postgresPassword: flyte
  postgresDatabase: flyte

storage:
  type: s3
  bucketName: my-s3-bucket
  s3:
    endpoint: http://minio.flyte.svc.cluster.local:9000
    region: us-east-1
    authType: accesskey
    accessKey: minioadmin
    secretKey: minioadmin

db:
  datacatalog:
    database:
      port: 5432
      username: flyte
      host: postgres.flyte.svc.cluster.local
      dbname: flyte
      password: flyte
  admin:
    database:
      port: 5432
      username: flyte
      host: postgres.flyte.svc.cluster.local
      dbname: flyte
      password: flyte
  syncresources:
    database:
      port: 5432
      username: flyte
      host: postgres.flyte.svc.cluster.local
      dbname: flyte
      password: flyte

console:
  replicas: 1

propeller:
  replicas: 1
