apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: flyte
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: minio.local.flyte.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio            # must match your Minio service name!
            port:
              number: 9000